# Generated by Django 3.2a1 on 2021-02-24 15:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('reportsapp', '0003_auto_20210224_1551'),
    ]

    operations = [
        migrations.AlterField(
            model_name='costs',
            name='date_cost',
            field=models.DateField(verbose_name=['%Y-%m-%d']),
        ),
    ]
