# Generated by Django 3.2a1 on 2021-02-25 09:19

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('reportsapp', '0006_alter_costs_cost_id'),
    ]

    operations = [
        migrations.RenameField(
            model_name='costs',
            old_name='cost_id',
            new_name='id',
        ),
    ]
