# Generated by Django 3.2a1 on 2021-02-26 09:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('reportsapp', '0007_rename_cost_id_costs_id'),
    ]

    operations = [
        migrations.AddField(
            model_name='costs',
            name='shipping_per_unit',
            field=models.FloatField(null=True),
        ),
    ]
