# Generated by Django 3.2a1 on 2021-03-03 12:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('reportsapp', '0008_costs_shipping_per_unit'),
    ]

    operations = [
        migrations.CreateModel(
            name='FixedCosts',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('name', models.CharField(max_length=200, null=True)),
                ('date', models.DateField(null=True, verbose_name=['%Y-%m-%d'])),
                ('quantity', models.IntegerField(null=True)),
                ('value', models.FloatField(null=True)),
            ],
            options={
                'abstract': False,
            },
        ),
    ]
