# Generated by Django 3.2a1 on 2021-03-18 14:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('reportsapp', '0013_createsuperuser'),
    ]

    operations = [

        migrations.AddField(
            model_name='costs',
            name='unit_cost',
            field=models.FloatField(null=True),
        ),
        migrations.AddField(
            model_name='costs',
            name='unit_cost_pln',
            field=models.FloatField(null=True),
        )

    ]
