# Generated by Django 3.2a1 on 2021-03-22 11:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('reportsapp', '0014_auto_20210318_1517'),
    ]

    operations = [

        migrations.CreateModel(
            name='HistoricalWarehouse',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('product_name', models.CharField(max_length=200, null=True)),
                ('product_category', models.CharField(max_length=200, null=True)),
                ('quantity', models.FloatField(null=True)),
                ('Unit_price', models.FloatField(null=True)),
                ('stock_value', models.FloatField(null=True)),
                ('date', models.DateField(null=True, verbose_name=['%Y-%m-%d'])),
            ],
            options={
                'db_table': 'reportsapp_historical_warehouse',
                'managed': True,
            },
        ),
        migrations.AlterModelOptions(
            name='fixedcosts',
            options={'managed': True},
        )

    ]
