# Generated by Django 3.2a1 on 2021-03-25 11:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('reportsapp', '0016_auto_20210323_1205'),
    ]

    operations = [

    ]
