# Generated by Django 3.2a1 on 2021-03-29 12:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('reportsapp', '0017_auto_20210325_1244'),
    ]

    operations = [
        migrations.AddField(
            model_name='costs',
            name='net_cost_pln',
            field=models.FloatField(null=True),
        ),
        migrations.AddField(
            model_name='costs',
            name='net_cost_usd',
            field=models.FloatField(null=True),
        ),
    ]
