# Generated by Django 3.2a1 on 2021-03-29 13:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('reportsapp', '0018_auto_20210329_1433'),
    ]

    operations = [

        migrations.AddField(
            model_name='costs',
            name='invoice_no',
            field=models.CharField(max_length=200, null=True),
        )
    ]
